// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/blog/comments/proto/comments.proto

package comments

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	// post to comment on
	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// message to leave
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8266712419156109, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8266712419156109, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request)(nil), "comments.Request")
	proto.RegisterType((*Response)(nil), "comments.Response")
}

func init() {
	proto.RegisterFile("github.com/micro/services/blog/comments/proto/comments.proto", fileDescriptor_8266712419156109)
}

var fileDescriptor_8266712419156109 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xce, 0x31, 0xcf, 0x82, 0x40,
	0x0c, 0x06, 0xe0, 0x8f, 0x2f, 0x06, 0xb0, 0x9b, 0xb7, 0x48, 0x9c, 0x0c, 0x93, 0x13, 0x4d, 0x74,
	0x94, 0xcd, 0xc9, 0x15, 0x7f, 0x80, 0x81, 0xa3, 0xc1, 0x4b, 0x3c, 0x8a, 0xf4, 0xe0, 0xf7, 0x1b,
	0x4f, 0x20, 0x8e, 0x4f, 0x9b, 0xf6, 0x7d, 0x21, 0x6f, 0x8c, 0x7b, 0x0c, 0x55, 0xa6, 0xd9, 0xa2,
	0x35, 0xba, 0x67, 0x14, 0xea, 0x47, 0xa3, 0x49, 0xb0, 0x7a, 0x72, 0x83, 0x9a, 0xad, 0xa5, 0xd6,
	0x09, 0x76, 0x3d, 0x3b, 0x5e, 0x98, 0x79, 0xaa, 0x78, 0x76, 0x9a, 0x43, 0x54, 0xd0, 0x6b, 0x20,
	0x71, 0x6a, 0x0b, 0x51, 0xc7, 0xe2, 0xee, 0xa6, 0x4e, 0x82, 0x7d, 0x70, 0x58, 0x17, 0xe1, 0x87,
	0xd7, 0x5a, 0x25, 0x10, 0x59, 0x12, 0x29, 0x1b, 0x4a, 0xfe, 0xfd, 0x62, 0x66, 0x0a, 0x10, 0x17,
	0x24, 0x1d, 0xb7, 0x42, 0xc7, 0x33, 0xc4, 0x97, 0xe9, 0xab, 0x42, 0x58, 0xdd, 0xca, 0x91, 0xd4,
	0x26, 0x5b, 0x82, 0xa7, 0x94, 0x9d, 0xfa, 0x1d, 0x7d, 0x4f, 0xd3, 0xbf, 0x2a, 0xf4, 0xbd, 0x4e,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x41, 0xc4, 0x9e, 0xd7, 0x00, 0x00, 0x00,
}
