// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/places.proto

package places

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Places service

func NewPlacesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Places service

type PlacesService interface {
	// Save a set of places
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
	// Last places for a set of users
	Last(ctx context.Context, in *LastRequest, opts ...client.CallOption) (*ListResponse, error)
	// Near returns the places near a point at a given time
	Near(ctx context.Context, in *NearRequest, opts ...client.CallOption) (*ListResponse, error)
	// Read places for a group of users between two points in time
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ListResponse, error)
}

type placesService struct {
	c    client.Client
	name string
}

func NewPlacesService(name string, c client.Client) PlacesService {
	return &placesService{
		c:    c,
		name: name,
	}
}

func (c *placesService) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error) {
	req := c.c.NewRequest(c.name, "Places.Save", in)
	out := new(SaveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placesService) Last(ctx context.Context, in *LastRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Places.Last", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placesService) Near(ctx context.Context, in *NearRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Places.Near", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placesService) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Places.Read", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Places service

type PlacesHandler interface {
	// Save a set of places
	Save(context.Context, *SaveRequest, *SaveResponse) error
	// Last places for a set of users
	Last(context.Context, *LastRequest, *ListResponse) error
	// Near returns the places near a point at a given time
	Near(context.Context, *NearRequest, *ListResponse) error
	// Read places for a group of users between two points in time
	Read(context.Context, *ReadRequest, *ListResponse) error
}

func RegisterPlacesHandler(s server.Server, hdlr PlacesHandler, opts ...server.HandlerOption) error {
	type places interface {
		Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error
		Last(ctx context.Context, in *LastRequest, out *ListResponse) error
		Near(ctx context.Context, in *NearRequest, out *ListResponse) error
		Read(ctx context.Context, in *ReadRequest, out *ListResponse) error
	}
	type Places struct {
		places
	}
	h := &placesHandler{hdlr}
	return s.Handle(s.NewHandler(&Places{h}, opts...))
}

type placesHandler struct {
	PlacesHandler
}

func (h *placesHandler) Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error {
	return h.PlacesHandler.Save(ctx, in, out)
}

func (h *placesHandler) Last(ctx context.Context, in *LastRequest, out *ListResponse) error {
	return h.PlacesHandler.Last(ctx, in, out)
}

func (h *placesHandler) Near(ctx context.Context, in *NearRequest, out *ListResponse) error {
	return h.PlacesHandler.Near(ctx, in, out)
}

func (h *placesHandler) Read(ctx context.Context, in *ReadRequest, out *ListResponse) error {
	return h.PlacesHandler.Read(ctx, in, out)
}
