// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/meme.proto

package meme

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Meme service

func NewMemeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Meme service

type MemeService interface {
	Templates(ctx context.Context, in *TemplatesRequest, opts ...client.CallOption) (*TemplatesResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error)
}

type memeService struct {
	c    client.Client
	name string
}

func NewMemeService(name string, c client.Client) MemeService {
	return &memeService{
		c:    c,
		name: name,
	}
}

func (c *memeService) Templates(ctx context.Context, in *TemplatesRequest, opts ...client.CallOption) (*TemplatesResponse, error) {
	req := c.c.NewRequest(c.name, "Meme.Templates", in)
	out := new(TemplatesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memeService) Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error) {
	req := c.c.NewRequest(c.name, "Meme.Generate", in)
	out := new(GenerateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Meme service

type MemeHandler interface {
	Templates(context.Context, *TemplatesRequest, *TemplatesResponse) error
	Generate(context.Context, *GenerateRequest, *GenerateResponse) error
}

func RegisterMemeHandler(s server.Server, hdlr MemeHandler, opts ...server.HandlerOption) error {
	type meme interface {
		Templates(ctx context.Context, in *TemplatesRequest, out *TemplatesResponse) error
		Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error
	}
	type Meme struct {
		meme
	}
	h := &memeHandler{hdlr}
	return s.Handle(s.NewHandler(&Meme{h}, opts...))
}

type memeHandler struct {
	MemeHandler
}

func (h *memeHandler) Templates(ctx context.Context, in *TemplatesRequest, out *TemplatesResponse) error {
	return h.MemeHandler.Templates(ctx, in, out)
}

func (h *memeHandler) Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error {
	return h.MemeHandler.Generate(ctx, in, out)
}
