// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/answer.proto

package answer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Answer service

func NewAnswerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Answer service

type AnswerService interface {
	Question(ctx context.Context, in *QuestionRequest, opts ...client.CallOption) (*QuestionResponse, error)
}

type answerService struct {
	c    client.Client
	name string
}

func NewAnswerService(name string, c client.Client) AnswerService {
	return &answerService{
		c:    c,
		name: name,
	}
}

func (c *answerService) Question(ctx context.Context, in *QuestionRequest, opts ...client.CallOption) (*QuestionResponse, error) {
	req := c.c.NewRequest(c.name, "Answer.Question", in)
	out := new(QuestionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Answer service

type AnswerHandler interface {
	Question(context.Context, *QuestionRequest, *QuestionResponse) error
}

func RegisterAnswerHandler(s server.Server, hdlr AnswerHandler, opts ...server.HandlerOption) error {
	type answer interface {
		Question(ctx context.Context, in *QuestionRequest, out *QuestionResponse) error
	}
	type Answer struct {
		answer
	}
	h := &answerHandler{hdlr}
	return s.Handle(s.NewHandler(&Answer{h}, opts...))
}

type answerHandler struct {
	AnswerHandler
}

func (h *answerHandler) Question(ctx context.Context, in *QuestionRequest, out *QuestionResponse) error {
	return h.AnswerHandler.Question(ctx, in, out)
}
