name: Downstream

# Alert downstream repos
# [service].proto and examples.json are the only files that affect how the m3o clients generator 
# will generate clients. Any internal changes to the service or how the service is implemented 
# internally is not a concern and will not affect how internally m3o clients work.
# Also, take under consideration this note https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#git-diff-comparisons
on:
  push:
    paths:
      - '**/README.md'
      - '**.proto'
      - '**/examples.json'
      - '**/publicapi.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Alert M3O
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/m3o/m3o/dispatches -d '{"event_type":"micro_services"}'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Alert M3O scheduler
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/m3o/m3o/dispatches -d '{"event_type":"build_m3o_client"}'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
