name: Downstream

# Alert downstream repos
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Alert M3O
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/m3o/m3o/dispatches -d '{"event_type":"micro_services"}'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
