name: Initiate Public API Publisher

on:
  push:
    paths:
      - '**.proto'
      - '**/examples.json'
      - '**/publicapi.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # triggering m3o/m3o/.github/workflows/publishapi.yml
      - name: Initiate API Publisher
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/m3o/m3o/dispatches -d '{"event_type":"public_api_publisher"}'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}